### ISSUE TITLE
AttributeError: module 'correlation' has no attribute 'ModuleCorrelation'

### ISSUE THREAD

**Issue by wine3603** [sniklaus/pytorch-pwc#12]
Hi man, I am using pythorch with python 3.6 cuda 8.0,
when I run 

`python run.py`

I got this error: 

> Traceback (most recent call last):
>   File "run.py", line 293, in <module>
>     moduleNetwork = Network().cuda().eval()
>   File "run.py", line 268, in __init__
>     self.moduleTwo = Decoder(2)
>   File "run.py", line 170, in __init__
>     self.moduleCorrelation = correlation.ModuleCorrelation()
> AttributeError: module 'correlation' has no attribute 'ModuleCorrelation'

```
Could you help me ?

**Comment by sniklaus** [comment]
Have you seen #7?

As a quick sanity check, could you run `python --version` and let me know what it prints?

**Comment by wine3603** [comment]
Thanks a  lot!!!
fixed it by installing cupy-cuda80 !

**Comment by yuanjunchai** [comment]
Yeah, I solve this problem by installing cupy-cuda100(For CUDA 10.0). More details refer to https://cupy.chainer.org/

**Comment by liubai01** [comment]
For those who used Ubuntu18, Please use cupy-cuda101(100 may also work). Or you will be faced with weird CompileException in cupy-cuda91 or earlier. Hope someone faced with the same problem will see this issue:).

**Comment by yuanjunchai** [comment]
> For those who used Ubuntu18, Please use cupy-cuda101(100 may also work). Or you will be faced with weird CompileException in cupy-cuda91 or earlier. Hope someone faced with the same problem will see this issue:).

Get it! Thank you!
