### ISSUE TITLE
optical flow upsampling 

### ISSUE THREAD

**Issue by zjxyz** [sniklaus/pytorch-pwc#13]
hi,
I would like to ask why the optical flow upsampling is multiplied by 0.65, 1.25, 2.5, 5. The original paper does not seem to mention it.
Thank.

**Comment by sniklaus** [comment]
It is mentioned in the implementation details section: "Note that we do not further scale the supervision signal at each level, the same as [15]. As a result, we need to scale the upsampled flow at each pyramid level for the warping layer. For example, at the second level, we scale the upsampled flow from the third level by a factor of 5 (= 20/4) before warping features of the second image." https://arxiv.org/abs/1709.02371

**Comment by zjxyz** [comment]
Thanks for your reply.
I understand why the optical flow upsampling is multiplied by 0.65, 1.25, 2.5, 5.
In addition, Why does the optical flow upsampling not use linear interpolation, but use nn.ConvTranspose2d, through the layer with variables, the optical flow will not find changes?

**Comment by sniklaus** [comment]
Different types of upsampling can be implemented using transposed convolutions, one just needs to initialize the kernel appropriately and fix its weights. For a possible kernel that performs bilinear upsampling, you can have a look at: http://caffe.berkeleyvision.org/doxygen/classcaffe_1_1BilinearFiller.html

**Comment by zjxyz** [comment]
Thanks for your reply!
