### ISSUE TITLE
How to do forward warping using im1 and flow?

### ISSUE THREAD

**Issue by HopLee6** [sniklaus/pytorch-pwc#14]
Given the first image and the forward flow, how can I perform forward warping to get im2?

**Comment by sniklaus** [comment]
I am afraid PWC-Net does backward warping, not forward warping: https://github.com/sniklaus/pytorch-pwc/blob/d8d55b26a2d429e3cd8429ccbe78974001da885b/run.py#L149

**Comment by HopLee6** [comment]
In your paper "Context-aware Synthesis for Video Frame Interpolation", you use forward warping, so will please release your code of this paper?
