### ISSUE TITLE
Use correlation as loss

### ISSUE THREAD

**Issue by bkvie** [sniklaus/pytorch-pwc#15]
correlation(image1, image2) outputs a multidimensional tensor, would it be possible to produce a scalar that can be used as a loss. I.e deform image 1 and minimise negative correlation between image1, image2.

summing up over all dimensions doesn't work.

**Comment by sniklaus** [comment]
Very interesting idea! I am not an expert in optical flow estimation, so my insights into this behavior are limited. I would thus encourage you to bring this up in the official repo: https://github.com/NVlabs/PWC-Net
