### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by donnydonny123** [sniklaus/pytorch-pwc#18]
Hi @sniklaus ,

In the original PWC-net paper, PWC-net's processing time is about 28ms.
![image](https://user-images.githubusercontent.com/12712998/53856568-608b3880-400d-11e9-8fc0-650dd999ec39.png)

But when I measured the time passed in `run.py`'s [estimate function](https://github.com/sniklaus/pytorch-pwc/blob/master/run.py#L315) and [moduleNetwork](https://github.com/sniklaus/pytorch-pwc/blob/master/run.py#L301), they cost about 330ms for estimate function and 173ms for moduleNetwork, which is too large to ignore.

I want to know that is there a reason that causes this issue. Thanks!

**Comment by sniklaus** [comment]
What is the input resolution for the table that you quoted? And which graphics card are you using?

**Comment by donnydonny123** [comment]
Hi, 
In the original paper's conclusion, 1024*436 images is used for benchmark.
The command I am using is the same as provided in https://github.com/sniklaus/pytorch-pwc#usage ,
Which is `python run.py --model default --first ./images/first.png --second ./images/second.png --out ./out.flo`
GPU is GTX 1080 ti.
Thank you for your reply.

**Comment by sniklaus** [comment]
Interesting find, thank you for bringing this up! Calling `moduleNetwork` in a for loop using the provided images clocks in at around 130 ms per estimate on my 1080 Ti, still much too slow. Note to everyone reading this and who might not be aware of the asynchronous computation nature of GPU computing, making sure to use `torch.cuda.synchronize()` to get the correct timing. Have you tried benchmarking the official release? If so, what is the timing you get? Thanks!

**Comment by sniklaus** [comment]
Closing the issue due to inactivity, I would still love to hear more about this though!
