### ISSUE TITLE
An error regarding the. flo file

### ISSUE THREAD

**Issue by huaxiaojian1997** [sniklaus/pytorch-pwc#20]
Hello,@sniklaus 
I installed pytorch-pwc according to your instructions. I successfully generated the. flo file, but I encountered a problem. After I visualized the. flo file and converted it to png file, I found the lower part of the picture was covered. I am not sure what this is. Can you help me?
![myplot_first second](https://user-images.githubusercontent.com/38944316/54590731-b7f4c400-4a63-11e9-8737-39388c0b75b2.png)
![myplot_frame1 frame2](https://user-images.githubusercontent.com/38944316/54590732-b7f4c400-4a63-11e9-88ce-dfde6dc60e87.png)

**Comment by sniklaus** [comment]
Looks like a bug when reading the `.flo` file. Have you tried using `cv2.optflow.readOpticalFlow`?

**Comment by huaxiaojian1997** [comment]
May I ask if the cv2.optflow.readOpticalFlow you mentioned is the file in OpenCV 3.4?

**Comment by sniklaus** [comment]
Seems like it: https://docs.opencv.org/3.4.0/d7/df9/namespacecv_1_1optflow.html

It might be part of `opencv_contrib` though, so your mileage may vary.

**Comment by huaxiaojian1997** [comment]
I used the program of OPTICAL FLOW TOOLKIT v0.1 on GitHub to convert. flo files into png files. I will try OpenCV to convert, thank you
