### ISSUE TITLE
I want to fine-tune PWC on ChairSDHom data-set

### ISSUE THREAD

**Issue by vivasvan1** [sniklaus/pytorch-pwc#21]
Hi sniklaus.I am vivasvan.
I am a beginner.
Can you guide me on how to this fine-tune PWC-Net on ChairSDHom dataset?
Your help will be really appreciated.
Thank you so much

**Comment by sniklaus** [comment]
Thank you for being interested in my reimplementation of PWC-Net! However, I am afraid that I do not provide any training or fine-tuning portion. I would thus recommend that you have a look at the official repository of PWC-Net: https://github.com/NVlabs/PWC-Net

**Comment by fjchange** [comment]
@vivasvan1 Have you successfully fine-tuned the model? 
I want that model too, could you share? Thanks
