### ISSUE TITLE
Performance compared to Flownet2.0

### ISSUE THREAD

**Issue by Zealoe** [sniklaus/pytorch-pwc#26]
I found the flow produced by pwcnet is more blurry than that of  flownet2.0. Is it supposed to perform worse? 
Image: 
![5_3](https://user-images.githubusercontent.com/30797481/62670671-97071e00-b9c6-11e9-9b26-3fa2fad90c9d.png)
![5_13](https://user-images.githubusercontent.com/30797481/62670673-98d0e180-b9c6-11e9-8bad-e226b170deb5.png)
Flow by Flownet2.0:
![p](https://user-images.githubusercontent.com/30797481/62670717-b69e4680-b9c6-11e9-9b91-a46cd58a9230.png)
Image warped by Flownet2.0:
![paa](https://user-images.githubusercontent.com/30797481/62670758-d6ce0580-b9c6-11e9-9283-9718ea03a820.png)
Flow by PWCnet:
![1](https://user-images.githubusercontent.com/30797481/62670774-e4838b00-b9c6-11e9-8a54-4c40c0de5adf.png)
Image warped by PWCnet:
![2](https://user-images.githubusercontent.com/30797481/62670780-ed745c80-b9c6-11e9-9c38-1c6f59c1c81b.png)

**Comment by sniklaus** [comment]
My apologies, but I am afraid that I am not one of the authors of PWC-Net and would thus recommend you raise your question in the official repository: https://github.com/NVlabs/PWC-Net
