### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by JohnnieXDU** [sniklaus/pytorch-pwc#31]
Hi, thanks for convert the model from caffe to pytorch. But the weights "network-default.pytorch" you uploaded is for which dataset? KITTI or Sintel? 

Besides, the EPE calculated from "network-default.pytorch" is quite far from the original paper. I am not sure that the EPE should be computed between the estimated flow and ground truth flow, or between estimated flow and 20*ground truth flow?

Thanks!

**Comment by sniklaus** [comment]
Please see: #23, #13, #9

The `default` model refers to the official `pwc_net.caffemodel`.
The `chairs-things` model refers to the official `pwc_net_chairs_things.caffemodel`.
