### ISSUE TITLE
the final optical flow is multiply by 20,Why multiply by 20，not 40？

### ISSUE THREAD

**Issue by l2009312042** [sniklaus/pytorch-pwc#32]
tensorFlow = 20.0 * torch.nn.functional.interpolate(input=moduleNetwork(tensorPreprocessedFirst, tensorPreprocessedSecond), size=(intHeight, intWidth), mode='bilinear', align_corners=False)

in the paper ，the author say "We scale the ground truth ﬂow by 20 and downsample it to obtain the supervision signals at different levels.",

and " our model outputs a quarter resolution optical ﬂow and uses bilinear interpolation to obtain the full-resolution optical ﬂow.",

the output flow  interpolation to full-resolution optical flow ,why it not multiply by 2?

**Comment by sniklaus** [comment]
I ported the official Caffe model, which multiplies by 20 as follows.

https://github.com/NVlabs/PWC-Net/blob/864d2e9fb3f60f9af99f4ea72943b1ff5d472202/Caffe/model/pwc_net_test.prototxt#L2924

For additional questions, you might want to direct your question at the authors of PWC-Net.
