### ISSUE TITLE
Is it possible to process bigger image size?

### ISSUE THREAD

**Issue by kaishijeng** [sniklaus/pytorch-pwc#37]
Current code has limitation of 1024x436.  Can it change to handle large size image, like 1920x1080?

Thanks,

**Comment by sniklaus** [comment]
What stops you from changing the following lines?

https://github.com/sniklaus/pytorch-pwc/blob/cf0d2f2cbef4bcb0f6cbf09011960a4899d77dec/run.py#L293-L294

**Comment by kaishijeng** [comment]
OK, I will try these 2 line changes.
One more question about backwarp in run.py. I will use the following call, backwarp(tenFirst, tenOutput), in run.py and got errors below:

  File "run.py", line 48, in backwarp
    tenHorizontal = torch.linspace(-1.0, 1.0, tenFlow.shape[3]).view(1, 1, 1, tenFlow.shape[3]).expand(tenFlow.shape[0], -1, tenFlow.shape[2], -1)
IndexError: tuple index out of range

Do you know why? 

Thanks,

**Comment by sniklaus** [comment]
You are the first to report such an issue, so I am not sure what the reason for this exception is. Are your images grayscale by chance?

**Comment by kaishijeng** [comment]
No, my images are color.

**Comment by sniklaus** [comment]
Do the provided images work?

**Comment by kaishijeng** [comment]
I got the same error even I use first.png and second.png  in images directory.

 python run.py --model default --first images/first.png --second images/second.png --out ./out.flo

**Comment by sniklaus** [comment]
Can you share your `run.py` with us?

**Comment by kaishijeng** [comment]
See the attachment of run.py. 
I just add backwarp function call to the end of your run.py
[run.zip](https://github.com/sniklaus/pytorch-pwc/files/4608226/run.zip)

**Comment by sniklaus** [comment]
I see, so you are added code and that code does not work. My apologies, but I unfortunately do not have the time to support such endeavors. I am only providing a reference implementation as is. I am hence closing this issue since you seem to be able to run the code on arbitrary input sizes now, after having commented out the acknowledgement asserts.
