### ISSUE TITLE
About the pre-trained model

### ISSUE THREAD

**Issue by qinzhang2016** [sniklaus/pytorch-pwc#38]
Hi! Thank you very much for the code. I just have a question about the pre-trained model. Is the network-chairs-things model pre-trained on the Flyingchairs dataset and Flyingthings3D dataset? How about the default model? What dataset is it pre-trained on? Looking forward to your reply! Many thanks!

**Comment by sniklaus** [comment]
Please see: #31, #23, #13, #9
