### ISSUE TITLE
output of the run.py

### ISSUE THREAD

**Issue by ShashiAdhikari** [sniklaus/pytorch-pwc#41]
how do you check the output of the run.py?
 line no:32 of run.py

arguments_strOut = './out.flo'

**Comment by sniklaus** [comment]
Could you elaborate on what you mean by "check the output"?

**Comment by ShashiAdhikari** [comment]
> Could you elaborate on what you mean by "check the output"?
how to check the file after we run the run.py file

**Comment by ShashiAdhikari** [comment]
> Could you elaborate on what you mean by "check the output"?

Run.py runs with no issue how do I know what is the ouput

**Comment by sniklaus** [comment]
If you didn't specify `--out` when running `run.py` then the estimated optical flow will be stored in `out.flo`. To read a `.flo` file, you can for example consider the following: https://stackoverflow.com/a/28016469
