### ISSUE TITLE
Can it test in CPU device?

### ISSUE THREAD

**Issue by bugczw** [sniklaus/pytorch-pwc#46]
In the project, in the file _correlation/correlation.py_, it uses a module called _cupy_. However, _cupy_ is based on cuda, which means that it needs to contain GPU. However, in most macOS computers, _cuda_ and _cupy_ cannot be supported. 
So, if I want to test this project without cuda, is there any way to achieve？Or is there any method that does not use _cupy_ module to implement the _correlation_ function?

**Comment by sniklaus** [comment]
To make it run on a CPU, you would have to rewrite `correlation.py` accordingly. For more details, please see #39
