### ISSUE TITLE
Generalization to unseen data

### ISSUE THREAD

**Issue by NagabhushanSN95** [sniklaus/pytorch-pwc#48]
Hi,

Thanks for this work. I was having issues setting up the official version, but yours was very simple and easy. 

I'm wondering how well would this model generalize to unseen data. I tried on a couple of frames from UCF-101 dataset and the results were not great. Among the other models you've, do any of them perform better on UCF-101 dataset?

**Comment by sniklaus** [comment]
Thanks for giving my reimplementations a try! I am afraid that I have no knowledge/intuition how well these generalize, so you will probably just have to give it a try yourself. My apologies.
