### ISSUE TITLE
Save flow as image (RGB)

### ISSUE THREAD

**Issue by Wazaki-Ou** [sniklaus/pytorch-pwc#5]
Hello there,

I was wondering if there is a way to save the flow between two images as an image as well instead of saving it as a .flo file. Do you have any code for that or any recommendation ?

Thank you

**Comment by sniklaus** [comment]
You could adopt the visualization in the "Dense Optical Flow" section at the following link, which uses a color coding for the magnitude / angle: https://docs.opencv.org/3.4.0/d7/d8b/tutorial_py_lucas_kanade.html

**Comment by Wazaki-Ou** [comment]
Thank you !! I actually did it that way but the resulting RGB shows colors over s dark background as opposed to the example you give where the background is white.

**Comment by seanremy** [comment]
I've struggled to get that to work as expected. I visualized it another way, but it would be really nice to have the code snippet that generates the nice views you have.

**Comment by sniklaus** [comment]
I am afraid that the code in question originates from the Middlebury benchmark for optical flow, and I am not sure whether I am allowed to share it. However, you could get in touch with Daniel Scharstein and kindly ask him to share it with you as well.

**Comment by seanremy** [comment]
Ah, fair enough. Thanks!
