### ISSUE TITLE
In run.py, self.netSix has out_channels = 196. Paper says 192.

### ISSUE THREAD

**Issue by Etienne66** [sniklaus/pytorch-pwc#54]
I reviewed the Caffe code in `pwc_net_utils.py` and it also has `out_channels = 196`. However their paper says it is supposed to be `192`. See the 2nd 'Figure 4.' in [PWC-Net: CNNs for Optical Flow Using Pyramid, Warping, and Cost Volume](https://arxiv.org/pdf/1709.02371.pdf) or 'Fig. 11' in their paper [Models Matter, So Does Training: An Empirical Study of CNNs for Optical Flow Estimation](https://arxiv.org/pdf/1809.05571.pdf)

I'm guessing that can't be changed without retraining from scratch though. Does it even matter?

**Comment by sniklaus** [comment]
They probably meant to use 192 (2^7+2^6) in the code as stated in the paper but then accidentally used 196 instead. This cannot be changed without retraining, but it doesn't really matter either.
