### ISSUE TITLE
Cupy cuda error. 

### ISSUE THREAD

**Issue by mhmtsarigul** [sniklaus/pytorch-pwc#58]
Hello, 

I could not make it work with different combinations of cupy's and cudatoolkits. I have cuda 11.5. Should I install an older version of cuda? What are the dependencies?

Original error:
  ImportError: libnvrtc.so.11.1: cannot open shared object file: No such file or directory

another error, 

Original error:
  ImportError: /home/istek/.local/lib/python3.8/site-packages/cupy_backends/cuda/api/runtime.cpython-38-x86_64-linux-gnu.so: undefined symbol: cudaMallocAsync

and some other cuda errors for different versions.

**Comment by sniklaus** [comment]
You need to make sure that PyTorch uses the same CUDA toolkit version as CuPy as well as your system. You can check the CUDA version installed on your system with `nvcc --version`, for PyTorch you can do `print(torch.version.cuda)` and for CuPy you can do `cupy.show_config()`.
