### ISSUE TITLE
Comparison with official's implementation

### ISSUE THREAD

**Issue by yzcjtr** [sniklaus/pytorch-pwc#6]
Hi @sniklaus ,

Taking no account of modifications which have no impact on precision, such as coding style, what's the main factor that results in your implementation's improvement? Is it because of the correlation layer or something else? Thanks a lot.

**Comment by sniklaus** [comment]
The correlation layer is identical, it is just the weights that are different. The official PyTorch implementation initially was trained differently from the official Caffe version of PWC-Net. For this reason, I simply converted the official Caffe weights to PyTorch, thus making sure that it achieves the same quality.

**Comment by yzcjtr** [comment]
Thanks @sniklaus. Nice job.
