### ISSUE TITLE
How to change the cuda version of correlation.py to the python version

### ISSUE THREAD

**Issue by haizhian** [sniklaus/pytorch-pwc#62]
How to change the cuda version of correlation.py to the python version, I use PyTorch to calculate according to the same logic, but the final result does not correspond.I would be very grateful if the author wrote a PyTorch version, I really can't write a version that can run on the CPU

**Comment by sniklaus** [comment]
My apologies for not being able to provide a CPU-only version since I unfortunately don't have bandwidth to do so, maybe you could try reaching out to the authors of PWC-Net through their repository: https://github.com/NVlabs/PWC-Net
