### ISSUE TITLE
how to import frames of river videos into PWC-Net codes

### ISSUE THREAD

**Issue by hoseinCode** [sniklaus/pytorch-pwc#64]
hi according to your python codes, in first UAV videos  must extract to frames and Frames import to codes.
Now i have 9000 Frames that extracted from mavic air combo videos (from Iran- Gorgan city Rivers). 
please Note to below section of code:
arguments_strOne = './images/one.png'
arguments_strTwo = './images/two.png'
do i can import 9000 frames manually into above code?
arguments_strOne = './images/frameone.png'
arguments_strTwo = './images/frametwo.png'
arguments_strOne = './images/framethree.png'
arguments_strTwo = './images/framefour.png'

until last frame?
i.e i must import two consecutive frames into above section code manually?
it is time-consuming.
i am confused.
please guide me

**Comment by sniklaus** [comment]
What stops you from modifying the following part in the `run.py` to iterate over all the frames and estimate the flow between adjacent ones?

https://github.com/sniklaus/pytorch-pwc/blob/ed3af4f57d2409df97f74f012bd26a381ee454ed/run.py#L311-L324

If that is too slow you can batch multiple inputs but that requires more coding.

**Comment by hoseinCode** [comment]
Hi thanks
I think I should put two consecutive frames into below lines:
arguments-strone = /data/frameone
arguments-strtwo = /data/frametwo
and I should modify this section of codes،🤔

در تاریخ پنجشنبه ۲۷ ژوئیهٔ ۲۰۲۳،‏ ۱۸:۵۶ Simon Niklaus <
***@***.***> نوشت:

**Comment by hoseinCode** [comment]
Hi I have mistake excuse me
Lines of code are :
arguments_strone = /images/one.png
arguments_strtwo = /images/two.png
frame1 replaces one.png and frame2 replaces two.png
I should modify this lines of codes (26 ,27)
Yes?

در تاریخ جمعه ۲۸ ژوئیهٔ ۲۰۲۳،‏ ۱۶:۰۱ hosein alhosseiny ***@***.***>
نوشت:

**Comment by hoseinCode** [comment]
hi there is error as "GetoptError: option -f not recognized"
 in below code line:
`for strOption, strArgument in getopt.getopt(sys.argv[1:], '', [ strParameter[2:] + '=' for strParameter in sys.argv[1::2] ])[0]:`
i read that getopt is deprecated and argparse must be used instead.
i changed getopt to argparse  but i have problems with argparse . i read about argparse very much but i am confused now.
please help me for fix GetoptError

**Comment by hoseinCode** [comment]
hi i solved my error but now your scripts dont show any output in google colab. of course there is not any error.
i am confused why dont show any output?

**Comment by hoseinCode** [comment]
hi i defined a **for loop** in codes as following:
![for_loop](https://github.com/sniklaus/pytorch-pwc/assets/25387448/c564709e-85fc-47a8-8ebf-52bf3e3a5efa)
but the codes dont estimate flow between adjacent frames.
please help me.

**Comment by sniklaus** [comment]
My apologies, but I am unfortunately unable to provide such a level of support. Maybe try StackOverflow? Sorry!
