### ISSUE TITLE
Deprecation of cupy.cuda.compile_with_cache() in cupy 13.0

### ISSUE THREAD

**Issue by KeWang0622** [sniklaus/pytorch-pwc#67]
Hi Simon,
Thanks for putting up this repo, very helpful!
One little thing, the cupy.cuda.compile_with_cache() function is deprecated/removed from cupy 13.0 (released early this year).
It causes an error in the correlation function.
Any simple fix? I guess we can always go back to cupy 12.x to get around with it.
Thanks!

**Comment by sniklaus** [comment]
Thank you for bringing this up! I thought I fixed this in 997f42d21912592463014dce56731b56c39abc64 roughly two days ago, are you using the newest version?

**Comment by KeWang0622** [comment]
Oh! wonderful, I tried it last week I guess with the previous version, and I think we should be good with this fix! Thank you!

**Comment by sniklaus** [comment]
I'll close this issue for now then, please reopen it should you still have this issue - thanks!
