### ISSUE TITLE
 module 'correlation' has no attribute 'ModuleCorrelation'

### ISSUE THREAD

**Issue by taylover-pei** [sniklaus/pytorch-pwc#7]
When I try to run your code, errors happened like this:
![image](https://user-images.githubusercontent.com/27360803/46240211-9715b500-c3d6-11e8-9600-7e0172a26bf3.png)
I uese python3.6, pytorch0.4。So, what should I do to solve the problem. Looking forward to your reply. Thank you very much.

**Comment by sniklaus** [comment]
As a quick sanity check, could you run `python --version` and let me know what it prints?

**Comment by amjltc295** [comment]
I got the same error as well. It seems to happen when cupy is not installed correctly. 
I solved it by using ` pip install cupy-cuda90` to install cupy (follow the instruction of https://github.com/cupy/cupy), with Python 3.6.6 and Pytorch 0.4.1.
