### ISSUE TITLE
Can you offer the .flo to .png code?

### ISSUE THREAD

**Issue by taylover-pei** [sniklaus/pytorch-pwc#8]
You have done a good job. But I find that the output files did not include the .png file, so can you offer the .flo to .png file code? Thank you very much.

**Comment by sniklaus** [comment]
You could adopt the visualization in the "Dense Optical Flow" section at the following link, which uses a color coding for the magnitude / angle: https://docs.opencv.org/3.4.0/d7/d8b/tutorial_py_lucas_kanade.html
